api:
  curr_symb: btceur # "btceur" or "btcusd"
  start_date: "2024-01-01"
  end_date: "2024-01-04"
  step_sec: 3600 # 1 hour
  max_res: 1000
model:
  model_name: "amazon/chronos-t5-tiny"
  context_len: 24
  cols: ["close"]
